### ISSUE TITLE
Error in `getAccountInfo` return the `IllegalArgumentException` for any address with delegation and without active pending changes

### ISSUE THREAD

**Issue by horus20** [Concordium/concordium-java-sdk#306]
**Bug Description**
When I request information about any addresses with active delegation, but without pending operation I receive the exception.
In the `ClientV2MapperExtensions` interface I found 3 similar places 
```.pendingChange(to(stake.getPendingChange()))```
and if we don't have pending stake operations we get here default instance, of course it's not correct.
In one place this moment already fixed
```
.pendingChange(delegatorInfo.hasPendingChange()
    ? Optional.of(to(delegatorInfo.getPendingChange()))
    : Optional.empty())
```
I guess, this is more correct, and need to copy this approach to other similar places.

**Steps to Reproduce**
Request the `getAccountInfo` from api v2 for some address with the delegation, for example: 4pcKwXGJFWrWMMnmoGrNk4upY9j8vBEFgXVNzgJvKdEANTHW2i (testnet)

**Expected Result**
Account information with the information about delegation.

**Actual Result**
`IllegalArgumentException` in this method `ClientV2MapperExtensions` method `static PendingChange to(StakePendingChange pendingChange)` 

**Versions**
- SDK Version: 6.0.0 and 6.1.0

**Comment by EmilLa1** [comment]
Hi @horus20 
Thanks for reporting this issue. This is indeed a bug as there might not be any pending changes as you correctly point out.
