### ISSUE TITLE
Error in the `getBytes` method of the `com.concordium.sdk.responses.AccountIndex`

### ISSUE THREAD

**Issue by horus20** [Concordium/concordium-java-sdk#308]
**Bug Description**
We have UInt64 index in the `com.concordium.sdk.responses.AccountIndex` but in the `getBytes` method, we allocate only 2 bytes instead of 8.
I guess this `getBytes` method could be more simple
```
public byte[] getBytes() {
    return index.getBytes();
}
```

**Steps to Reproduce**
try to call a `getBytes` method from `ConfigureDelegationPayload` object.

**Expected Result**
array of bytes

**Actual Result**
java.nio.BufferOverflowException error

**Versions**
- SDK version 6.1.0

**Comment by EmilLa1** [comment]
Hi, thanks for reporting this bug. 

This is indeed a bug as you described. There's a PR here https://github.com/Concordium/concordium-java-sdk/pull/309 solving it, and it will be part of the next release.
