### ISSUE TITLE
Add offline transaction energy estimation

### ISSUE THREAD

**Issue by Radiokot** [Concordium/concordium-java-sdk#333]
Local energy estimation allows determining the transaction fee without making a wallet-proxy request. This helps when the transaction payload is too large to fit into a GET request.<br><br>How it is done in Rust:<br>[concordium-rust-sdk/src/types/transactions.rs at 01b00f7a82e62d3642be51282e6a89045727759d · Concordium/concordium-rust-sdk (github.com)](https://github.com/Concordium/concordium-rust-sdk/blob/01b00f7a82e62d3642be51282e6a89045727759d/src/types/transactions.rs#L1276)

**Comment by limemloh** [comment]
Most transactions are straight forward to implement.
But for the smart contract init- and update-transactions this can only be estimated by running the smart contract using our smart contract execution, which quickly could make this a complex task.

**Comment by Radiokot** [comment]
Found out it is already there: [Payload.java](https://github.com/Concordium/concordium-java-sdk/blob/150775c98ce9f2c542fe4539a3229f939eed0f23/concordium-sdk/src/main/java/com/concordium/sdk/transactions/Payload.java#L121)
