### ISSUE TITLE
Figure out the best way to replace the rust dependency.

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-java-sdk#53]
Currently the java sdk exposes ed25519 functionality via jni and a rust dependency. 

Replacing this with a native java dependency would make it easier to build and distribute the sdk. 

Example solutions each with their pros and cons. 

- Upgrade the java version from 8 to 15 (java supports ed25519 as of version 15)
- Backport the jdk 15 ed25519 implementation
https://github.com/openjdk/jdk15/tree/master/src/jdk.crypto.ec/share/classes/sun/security/ec/ed
- Other alternatives?

A new issue should be created for the actual work and implementation.

**Comment by abizjak** [comment]
Re-evaluate in autumn 2022.

The latest LTS version is Java 17 which was released in September 2021.

**Comment by EmilLa1** [comment]
Closed as the SDK will need to depend on https://github.com/Concordium/concordium-base in the future in order to support various transactions.
